# Generated by Django 4.0.4 on 2022-04-22 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invests', models.CharField(default=[('card', 'CARD'), ('bank transfer', 'BANK TRANSFER')], max_length=225)),
                ('withdraw', models.CharField(max_length=225)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('processed', 'PROCESSED')], max_length=225)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
