# Generated by Django 4.0.4 on 2022-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invests',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='withdraw',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAWAL')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('processed', 'PROCESSED')], default='PENDING', max_length=225, null=True),
        ),
    ]
