# Generated by Django 4.0.4 on 2022-06-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_type_transaction_transaction_type_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
